### ISSUE TITLE
SSL_do_handshake problems and Fix*

### ISSUE THREAD

**Issue by peterdegn** [nateuribe/Wazuh-IRIS-integration#1] opened 2023-10-15 00:01 UTC
13#13: *3899 SSL_do_handshake() failed (SSL: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:SSL alert number 48) while SSL handshaking, client:

there is a problem on the Iris server and the alerts are not comming in even whe aktive SSL

so the fix 

#OLD 
response = requests.post(hook_url, data=payload, headers={"Authorization": "Bearer " + api_key, "content-type": "application/json"})

#NEW
response = requests.post(hook_url, verify=False, data=payload, headers={"Authorization": "Bearer " + api_key, "content-type": "application/json"})

that will solve the problem and the events will pass over.

**Comment by nateuribe** [comment] 2023-10-16 18:35
Hi,
Looks like the issue is possibly due to the IRIS Docker container creating a self-signed certificate by default ([https://docs.dfir-iris.org/operations/configuration/#certificates](https://docs.dfir-iris.org/operations/configuration/#certificates)), hence why `requests.post` needs to be modified to disable certificate verification with `verify=False`.

I've gone ahead and updated the [README](https://github.com/nateuribe/Wazuh-IRIS-integration/blob/main/README.md) to include this detail for others that may also run into this issue.

Thanks for bringing up this issue and its solution.

**Comment by decyphertek-io** [comment] 2023-11-10 23:36
Send request to IRIS with SSL verification disabled:
----------------------------------------------------------------------
* Modify the last line of the python script
* response = requests.post(hook_url, data=payload, headers={"Authorization": "Bearer " + api_key, "content-type": 
  "application/json"}, verify=False)

**Comment by nateuribe** [comment] 2023-11-16 18:25
I previously opted not to make modification in the script as to not affect those who may be running the script in an environment where they have proper SSL certificates configured (i.e. production), and instead modified the README instructing on how to resolve the issue.

 That being said, do you think the change should still be made?

**Comment by nateuribe** [comment] 2024-04-20 01:32
Closing as the solution has been put under the [Installation](https://github.com/nateuribe/Wazuh-IRIS-integration?tab=readme-ov-file#installation) step of the [README](https://github.com/nateuribe/Wazuh-IRIS-integration/blob/main/README.md).

**Closed as completed by nateuribe** 2024-04-20 01:32 UTC
